### PR TITLE
issue #81 - move config to CmsBundle

### PR DESCRIPTION
**Pull request by bartdens**

### CODE REVIEW

**Comment by bartdens** [comment]
@kristofvc this one moves most config that belongs there to the CmsBundle

One thing I couldn't get to work is refer to bundle resources like this
`resource: "@CmsBundle/blah/`

Only for the routing it works, not in yaml's loaded by the bundle's services.yaml. Got no clue why as I found numerous samples of other bundles that use it. But it won't work for the CmsBundle for some reason...

**Comment by bartdens** [comment]
What I meant to say is that when this PR is merged this code should also move to the monorepo

**Comment by kristofvc** [comment]
@devartbvba you have to add an extension class and load the config there, if that’s what you mean’t, see doctrineextensions bundle

**Comment by bartdens** [comment]
> @devartbvba you have to add an extension class and load the config there, if that’s what you mean’t, see doctrineextensions bundle

Yeah which is the case, and I see in other bundles they use the same FileLocator than I do, which doesn't have a check for a location starting with "@", and still they manage to have it working, 

Now I added a temp hack in the Extension file, which makes is working (but without the "@CmsBundle/" in front of it). I hope to make it work later as I wanted...

**Review by kristofvc — APPROVED** [review]

**Pull request merged**
